swagger: "2.0"
info:
  description: "BDD Workshop"
  version: "1.0.0"
  title: "BDDWorkshop"
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

paths:
  /test:
    get:
      operationId: "helloworld.get"
      responses:
        200:
          description: "hello, world"